### ISSUE TITLE
align.py doesn't output nothing

### ISSUE THREAD

**Issue by andreapirone** [EggplantElf/IMSurReal#1]
I'm trying to use your neural network, but running 
`python3 IMSurReal/align.py data/UD/en_partut-ud-dev.conllu data/T1/en_partut-ud-train.conllu data/T1/en_partut-ud-train.gold.conllu`

seems that nothing go to the output.
At the end of the execution I get:
`# sents: 0`

How might I do?

**Comment by EggplantElf** [comment]
Hi, the first file should be `data/UD/en_partut-ud-train.conllu` instead of  `data/UD/en_partut-ud-dev.conllu`.
